anno_data_path: data/samples/ads_damage_1990-2022/anno_data.zarr
back_step: 5
chip_data_path: data/samples/ads_damage_1990-2022/chip_data.zarr
end_date: null
file_type: ZARR
ignore_size_limit: true
io_limit: 64
log_name: downloader
log_path: logs/ads_damage_1990-2022
meta_data_path: data/samples/ads_damage_1990-2022/meta_data.zarr
num_workers: 40
overlap_band: true
overwrite: false
pixel_edge_size: 269
reprojection: UTM
retries: 1
scale: 30
start_date: null
strata_map_path: data/samples/ads_damage_1990-2022/strata_map.yaml
