---
model: 
    class_path: SundialPrithvi
    init_args:
        weights_path: /mnt/c/Users/scone/sundial/src/backbones/prithvi/Prithvi_100M.pt
        num_classes: 2
        embed_dim: 768
        learning_rate: 0.0001
        mask_ratio: 0.0
        upscale_depth: 4
        prithvi:
            model_args:
                decoder_depth: 8
                decoder_embed_dim: 512
                decoder_num_heads: 16
                depth: 12
                embed_dim: 768
                img_size: 256
                in_chans: 6
                num_frames: 6
                num_heads: 12
                patch_size: 16
                tubelet_size: 1
            train_params:
                bands:
                - B2
                - B3
                - B4
                - B5
                - B6
                - B7
                data_mean:
                - 775.2290211032589
                - 1080.992780391705
                - 1228.5855250417867
                - 2497.2022620507532
                - 2204.2139147975554
                - 1610.8324823273745
                data_std:
                - 1281.526139861424
                - 1270.0297974547493
                - 1399.4802505642526
                - 1368.3446143747644
                - 1291.6764008585435
                - 1154.505683480695
                mask_ratio: 0.75
                random_cropping: true


data: 
    class_path: ChipsDataModule
    init_args: 
        batch_size: 32
        num_workers: 4
        mask_name: "overlap"
        base_year: null
        back_step: null
