---
start_date: "1985-06-01"
end_date: "2023-09-01"
file_type: "ZARR"
scale: 30
edge_size: 7500
reprojection: true
chip_data_path: "your/chip_data/path"
meta_data_path: "your/meta_data/path"
num_workers: 64
retries: 1
request_limit: 40
ignore_size_limit: true
io_lock: true
overwrite: false
log_path: "your/logs/path"
log_name: "sundial.downloader"
test: false
